### ISSUE TITLE
New name for `Note.offset` and other related terms

### ISSUE THREAD

**Issue by pmcharrison** [music-computing/amads#18]
`Note.start`

`Note.end`

`Note.dur`

**Comment by rbdannenberg** [comment]
My preference is to use delta for relative time offset, and start/stop for absolute time, and dur for stop - start. These are going to be either quarters or seconds, so no more "q" prefix.

**Comment by pmcharrison** [comment]
That sounds great to me actually!

**Comment by pmcharrison** [comment]
@rbdannenberg if we take your proposal, what does `end_offset` become? 

## Option 1

- `offset` becomes `delta`
- remove all references to `end_offset`, user has to use `e.delta` + `e.dur`

## Option 2 

- `offset` becomes `delta`
- `end_offset` becomes `delta_end`

## Option 3

- `offset` becomes `delta_start`
- `end_offset` becomes `delta_end`

I'm leaning slightly towards Options 2 and 3, maybe slightly towards 3, but what do you think?

**Comment by rbdannenberg** [comment]
I'd prefer Option 2. Somehow, `end_delta` seems better than `delta_end`, but if I think of it as  	
Δ*end*, given that `end` is defined as absolute time from the score beginning, then `delta_end` makes sense.

**Comment by pmcharrison** [comment]
Great, thanks! I will implement this now.

**Comment by pmcharrison** [comment]
I am trying it out in a few scripts, but struggling a little with readability. The term `delta` does not obviously connote time and so it's not obvious what the scripts are manipulating.

@rbdannenberg are you sure it's helpful to have separate attributes for these two types of time? Can we not just store absolute time for both child and parent, then if someone wants relative time they can subtract the parent's time? 

```py
note.start  # absolute time
note.start - note.measure.start  # relative time
```

**Comment by pmcharrison** [comment]
More generally, I have found already that it is worryingly easy to make mistakes when working with these representations if you forget which of the two types of timing you are working with (or relatedly, whether you have flattened the score or not)

**Comment by rbdannenberg** [comment]
I can't claim what's best, but the reasoning is that deltas are stored because they allow manipulations at higher levels without recomputing everything, e.g. if you insert a measure, you need to update deltas for subsequent measures, but changes stop at that level, whereas if you stored absolute times, *everything* would need to be updated. On the other hand, with weak links to parents, computing absolute start time is relatively fast: only proportional to depth in the fairly shallow hierarchy. Absolute time is a @property so that it looks like an attribute and the user doesn't have to be very aware of how things are actually stored.

I suppose there could be a set_start() method or even a start "setter" so, if you wanted, you could work in terms of absolute times, although if you are maniputing structures, you still have to understand the hierarchy, e.g. add notes to measures rather than parts if measures exist.

**Comment by pmcharrison** [comment]
I agree that we can wrap things such that the user experience is distinct from the underlying implementation. 
Currently we store everything in relative terms, and we compute the absolute representation on-demand. We could add a setter, like below --

```py
@property
def start(self):
    return self.delta + self.parent.delta

@start.setter
def start(self, value):
    self.delta = value - self.parent.start
```

and then users could write something like `note.start = 42`, and `delta` would be updated correspondingly.

My first question is, do we want to encourage users to use the relative representation at all, or should it be hidden away as an implementation detail? I am struggling to think of situations where the relative representation would be more readable than the absolute representation. I much prefer this:

```py
note.start - note.measure.start
```

to this:

```py
note.delta
```

because I think in the latter case it's hard to know what the delta is referring to.

My second question is, is it really true that the relative representation is a useful performance optimisation? You point out rightly that the relative representation is efficient for translating a parent container (e.g. a measure, or indeed a series of measures) in time. How often do we want to do this, though? I remember you saying that Scores should be treated as immutable, and that our operations should involve copying rather than in-place operations. If so, then translation won't be made (significantly) more efficient by a relative representation. Even if we forget about (im)mutability for a moment, in what scenarios do you anticipate us wanting to do such transpositions? The workflows in my mind all concern corpus analyses, where the score is fixed in advance, and I can't imagine wanting to insert passages within a score. Are there other cases where this might be desired? The only one I can think of is composition software, but I don't think that's what we're doing.

It's true that the relative representation does not bring much cost, efficiency-wise. Each time you need an absolute time you get a fixed overhead where you have to check parent times, but that should not be expensive. The main cost is readability, but this cost can be minimised by only exposing the absolute representation and only taking advantage of the relative representation internally for transposition operations.

What do you think, then -- would it be reasonable to make `delta` an internal attribute and only expose `start` and `end`? That would be easy to do without changing much code. More radically, we could drop `delta` altogether and just simplify things to the absolute representation (the rationale being that transpose operations are rare). Personally, I think that might be a reasonable simplification of the code, but perhaps unnecessary now that's implemented how it is.

**Comment by pmcharrison** [comment]
In fact, one big argument for me in favour of dropping the relative representation entirely would be that flattening a score would no longer be an expensive or complex operation. I think that the current complexity is unfortunate given that it's such a common operation. If we used an absolute representation, then we might be able to use a single score for everything, just with different accessors.

**Comment by rbdannenberg** [comment]
It seems common to refer to score positions as "measure 3 beat 2" which is a "natural" use of relative position.
I agree we're not expecting to emphasize score modifications, but taking slices of scores for analysis, constructing scores in the first place could result in making updates more like O(N^2) than O(N), so my intuition is to avoid even that possibility. I think there are other cases where changing scores could be part of an analysis operation. I just disagree on "hard to know what the delta refers to" -- it's just time offset within the parent. If it's hard to know what the parent is, it's easy to find out if you care, and if it matters, then you should probably either flatten the score (so then you know), or use note.start. I also don't think flattening is an expensive or complex operation -- I bet the cost would be almost identical for either representation since you are copying a lot of objects, and either way, flattening is O(N) for N notes. You could make `delta` internal, although I don't even know how visibility works in Python (can you grant visibility to those that want it?) and it seems like overkill to me.

**Comment by pmcharrison** [comment]
# Obtaining beat in bar

"Measure 3 beat 2" is a good use case to consider, yes. In other words, we want users to have easy access to the position of the note within the measure. However, I don't like the idea of encouraging this kind of code:

```py
beat = note.delta
```

Firstly, I don't think it's intuitive (without reading the documentation, how does the reader know that `delta`, a random Greek symbol, denotes time?). Secondly, I think it's dangerous, because we are just assuming that the note's parent is going to be a measure, but what if it's not? Best practice will be to write defensively, but is this really want we want to impose? Like this -- 

```py
match note.parent.__class__:
    case Part:
        raise ValueError("Cannot obtain the beat from a flattened score. Please use the original unflattened version."
    case Chord:
        chord = note.parent
        assert isinstance(chord.parent, Measure)
        beat = chord.delta
    case Measure:
        beat = note.delta
```

Aside from being unwieldy, this code is not future-proof, because what if one day we want to add something else into the parent hierarchy akin to Chord? Code such as the above will break.

This is what I mean by saying that I think it's hard to know what delta refers to, and that I don't want to encourage users to use delta. You say "it's just time offset within the parent", but firstly that's not obvious from the name, and secondly even if you know the definition, it's difficult to know for sure what the parent is, so you have to write all this checking code. Yes, it is "easy" according to a certain definition of the word, but it's ugly and verbose, and our goal should be to make these fundamental operations as concise and readable as possible.

Hence I would prefer to tell them to use `time` and refer explicitly to their reference points. For example:

```py
beat = note.start - note.measure.start
```
I think the above is both unambiguous and (relatively) future-proof. I would then say that we should avoid the use of delta wherever possible, because it is less readable and more error-prone.

# Private attributes

In Python, you would make delta private by renaming it to `_delta`. The underscore notation does not prevent access from the outside -- you can always write `note._delta` if you want -- but this is understood to be at the user's own risk. 

# Taking slices for analysis

This is a really important case you've raised, indeed. For example, I can imagine wanting to write something like this:

```py
sonata = import_xml("sonata.xml")
development = sonata.measures[31:64]
```

I think that this kind of list indexing is probably the most natural way for people to make such accesses.

You are saying that, when we perform such slicing, we should be updating the times of all the content such that the development starts at zero time (correct me if I'm wrong). This means that we need to copy the top level of the copied hierarchy, which here would be 32 Measure objects (mm. 32-64), and update their 32 time attributes.

My question is, is it really desirable to update the times in this way? What does it help us with? In my eyes, this is unnecessarily discarding information that might be useful to the analyst. If the analyst does want to compute the time relative to the start of the development, they can just write

```py
development_start = development[0].start
note.start - development_start
```

which I think is nice and explicit.

If we take this approach, then we make things a lot easier for ourselves, because we don't have to copy objects when creating slices, which IMO is an undesirable overhead both in terms of code complexity and computation time.

# Flattening

> I also don't think flattening is an expensive or complex operation -- I bet the cost would be almost identical for either representation since you are copying a lot of objects, and either way, flattening is O(N) for N notes. 

My main issue with flattening is the cognitive complexity, both in terms of the user and in terms of our own code. As explained above, the user needs to know whether the score they are working on is flattened or not because currently it affects how attributes are defined. We have to write code like `is_flattened_and_collapsed` and `is_flattened` to check this. We will have to be very careful when writing functions to make sure we test that they work properly with the different kinds of inputs. I see this as being a big overhead.

My proposal above means that we could actually drop the distinction between flattened and not-flattened scores. `Score.content` would support arbitrary nestings of lists, ranging from Staffs to Measures to Notes and anything in between. Then whenever you want flat content, e.g. a list of notes, you can just call `Score.find_all(Note)`, and you're done. This would make it easy to support arbitrary additional groupings in the future, for example if a user wanted to define something like `Section`. It would also make it easy to drop groupings, for example if a user decided they didn't like the idea of Staff being part of the hierarchy.
        
# Final thoughts

I apologise for getting us bogged down in these basic questions. However I do think these questions about the basic representation are very important. When we've talked about issues with music21 and partitura, the core sticking point has been that you've felt their representations are not up to scratch. If so, then we need to take our own representation approach very seriously, and I think therefore it's good for us to be discussing in this way

I know you have a lot on but I'm totally happy to do any refactoring myself, so you shouldn't see any of these options as involving more work for you.

**Comment by rbdannenberg** [comment]
There's a lot here, and I can't respond to everything before a meeting that's coming up. I'll be free at 11:30EST (4:30 GMT I believe) if we can talk then. To begin, I think we're talking about many small issues that can be resolved in multiple ways. Instead, we should zoom out to a bigger picture. E.g. is this really about "delta" being confusing? It seemed clear to me, but maybe it just needs to be called "delta_beat" or something? From a more high-level view, the notions of flattened score vs structured score comes out of discussions with Mark and also maps pretty well to actual data, considering MIDI, which may not have meaningful measures, vs. music XML where measures are not only defined but we want to retain them for analysis purposes. So if it's confusing to have notes in different contexts, is it better to have entirely different data structures for 2 types of scores? We could have FlatScore, FlatNote, etc., but that seems much worse to me. One of the motivations for flattened scores was initial conversations with Mark and out discussions of extracting the simplest possible data (e.g. just a list of pitches) from score structures to pass into analysis functions so that they did not have to deal with data structure details. I think now we're accomplishing that through `Score.find_all(Note)` in many cases. You could consider eliminating flattened scores altogether and just providing ways to access Scores as if they are flattened. In my opinion, learning about sophisticated abstractions is more complex than simply flattening the score. In general, "simplifying" by introducing layers of abstraction is not always successful in terms of actually making things easy.

**Comment by pmcharrison** [comment]
Thanks @rbdannenberg! Would be great to talk and 11:30 EST/4:30 GMT works for me. I will send you a Zoom link by email.

**Comment by pmcharrison** [comment]
Conclusion from discussion: we will keep the underlying implementation of `delta` and relative times, as it has served previous iterations of music software well. However, we will (gently) discourage users from accessing it and encourage them to use `start` and `end` instead to minimise ambiguity. It will then not matter for the user whether the score is flattened or collapsed, because start and end will be unaffected by that.

**Comment by pmcharrison** [comment]
I have now implemented this, it is on the main branch and tests are passing.
